#!/bin/python3

files = [   'src/mame/samsung/spc1000.cpp',
            'src/devices/bus/spc1000/neo.h',
            'src/devices/bus/spc1000/neo.cpp',
            'src/devices/bus/spc1000/spcbox.h',
            'src/devices/bus/spc1000/tap.h',
            'src/devices/bus/spc1000/tap.cpp',
            'scripts/src/bus.lua',
            'src/lib/util/options.cpp',
]

import os

home = os.path.expanduser("~")
for file in files:
    path = f'{home}/mame/{file}'
    print(path)
    os.remove(path)
    os.system(f'ln -s {home}/spc1000/mame/{file} ~/mame/{file}')
