#!/bin/bash
declare -a array=( "src/mame/samsung" "src/devices/bus/spc1000" "src/emu" "scripts/src" )
patchfile=mame.patch.$(date '+%y%m%d')
echo > $patchfile
for path in "${array[@]}" 
do 
    diff -urN mame_orig/$path mame/$path >> $patchfile
done
