#
# Makefile
#

CIRCLEHOME = ../circle

OBJS	= main.o kernel.o screen8.o tms9918.o lib.o

LIBS	= $(CIRCLEHOME)/lib/libcircle.a \
		  $(CIRCLEHOME)/addon/SDCard/libsdcard.a \
		  $(CIRCLEHOME)/addon/fatfs/libfatfs.a \
		  $(CIRCLEHOME)/lib/fs/libfs.a 

include $(CIRCLEHOME)/Rules.mk



