; SPC-1000 Baremetal Tape Loader Configuration
; Place this file as SD:/spcconfig.ini

; Global tape options
[tape]
; Rewind tape to start on system reset
rewind_on_reset=1

; Sync detection options
[sync]
zero_skip=50
pattern=11000000
precursor_zeros=15
start_offset=10


